### ISSUE TITLE
Does it work on windows ?

### ISSUE THREAD

**Issue by Paulo-21** [wiseaidev/rping#11]
Hello, just asking if it work on windows because i got this error 
![image](https://github.com/wiseaidev/rping/assets/34631206/6fd093f0-d2c3-41dc-990c-afb1432b77cc)

Win11
The terminal was run in admin mode.
and i did not run `sudo setcap cap_net_raw+ep ~/.cargo/bin/rping` because i m on windows

**Comment by wiseaidev** [comment]
Hello! Linux is my primary OS. I don't use Windows for development; I occasionally use it for CS2 gaming sessions with the boys. However, feel free to add support for Windows or contribute if you'd like.

**Comment by Paulo-21** [comment]
After several investigation and trys i have found this 
https://learn.microsoft.com/en-us/windows/win32/winsock/tcp-ip-raw-sockets-2?redirectedfrom=MSDN#limitations-on-raw-sockets

It 's seems that we cannot do anything with windows..
